### ISSUE TITLE
Only works once after installation

### ISSUE THREAD

**Issue by dnewcomb** [moovida/smash#31]
When I load Smash 1.2,it finds my location and allows me to see geopackage files I have loaded on my phone, which is great!.
When I close it:
1)  the location services continue to run
2) the second time I try to run it i just get a blank screen .
3) I can get around the blank screen by going into my android setting and manually killing location services for SMASH, but when I open SMash again i cannot do anything unti; location services are started again, and then i am back to the blank screen.
Running Moto G6 play with Android 9

**Comment by moovida** [comment]
Hi @dnewcomb , thanks for this report. This is huge. Sadly in the sense of huge mess.

I really need your help to reproduce this, since I want this to be fixed as soon as possible.

You are telling me that when you exit SMASH with the back button, after the exit prompt, the location service continues to run? And after that you just  run it again?

Can I ask you to backup the smash folder created in the storage and zip it. Then remove the original smash folder and then start smash up again? Please make sure the app is really killed before restarting it.

Thanks for any support you can give me.

**Comment by dnewcomb** [comment]
> Hi @dnewcomb , thanks for this report. This is huge. Sadly in the sense of huge mess.
> 
> I really need your help to reproduce this, since I want this to be fixed as soon as possible.
> 
> You are telling me that when you exit SMASH with the back button, after the exit prompt, the location service continues to run? 
Yes
And after that you just run it again?
I try to start Smash Again from the icon
> 
> Can I ask you to backup the smash folder created in the storage and zip it. Then remove the original smash folder and then start smash up again? Please make sure the app is really killed before restarting it.
I will reinstall smash and try to do this. 

> 
> Thanks for any support you can give me.

**Comment by dnewcomb** [comment]
[smash_contents.zip](https://github.com/moovida/smash/files/4685001/smash_contents.zip)
The only way to restart SMASH is to uninstall and reinstall
Attaching photos of symptoms.
![2020-05-26-164616](https://user-images.githubusercontent.com/2164971/82949740-1e337b80-9f72-11ea-9d16-5010ba9a0e3b.jpg)
![2020-05-26-164630](https://user-images.githubusercontent.com/2164971/82949760-268bb680-9f72-11ea-90b9-b7103ec3097c.jpg)
![2020-05-26-164724](https://user-images.githubusercontent.com/2164971/82949779-30151e80-9f72-11ea-8192-4c1258cd5b67.jpg)
![2020-05-26-164743](https://user-images.githubusercontent.com/2164971/82949795-360aff80-9f72-11ea-8ecd-c23b11bc5f6e.jpg)
![2020-05-26-164653](https://user-images.githubusercontent.com/2164971/82949820-3efbd100-9f72-11ea-8f30-56e3f66a0f7e.jpg)

**Comment by moovida** [comment]
Thanks a ton @dnewcomb , I have been able to reproduce on an android 9 device. It seems they were (more) affected.
I think I fixed this and rolled out a 1.2.1 version. I would appreciate if you could test it. If there are problems, feel free to reopen this issue.

**Comment by dnewcomb** [comment]
Thank you for being so prompt in working on this!  Google play still shows the 1.2.0 version.  I will check again later today.

**Comment by dnewcomb** [comment]
Andrea,
The good news is that I can open smash a 2nd time and it works.  The
flutter location service is still running in the background and I have to
do a force stop to completely close smash .

Doug

**Comment by dnewcomb** [comment]
OK,
I tried it a few more times and it is stopping cleanly now.

Doug

**Comment by dnewcomb** [comment]
Thank you for the fix!

Doug

**Comment by moovida** [comment]
Thanks for the report and test @dnewcomb 

I also noticed that the services takes some seconds to stop after closing. It should close cleanly, but we will have to keep this checked to make sure it doesn't do random things.
